src/Entity/Customer.php
<?php

namespace App\Entity;

use App\Repository\CustomerRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=CustomerRepository::class)
 */
class Customer
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $firstname;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $lastname;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $pseudo;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $adress;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $postCode;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $city;

     /**
     * @ORM\OneToMany(targetEntity=Transaction::class, mappedBy="customer")
     */
    private $transactions;

    public function __construct()
    {
        $this->transactions = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname): self
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(string $lastname): self
    {
        $this->lastname = $lastname;

        return $this;
    }

    public function getPseudo(): ?string
    {
        return $this->pseudo;
    }

    public function setPseudo(?string $pseudo): self
    {
        $this->pseudo = $pseudo;

        return $this;
    }

    public function getAdress(): ?string
    {
        return $this->adress;
    }

    public function setAdress(?string $adress): self
    {
        $this->adress = $adress;

        return $this;
    }

    public function getPostCode(): ?int
    {
        return $this->postCode;
    }

    public function setPostCode(?int $postCode): self
    {
        $this->postCode = $postCode;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(?string $city): self
    {
        $this->city = $city;

        return $this;
    }

    /**
     * @return Collection|Transaction[]
     */
    public function getTransactions(): Collection
    {
        return $this->transactions;
    }

    public function addTransaction(Transaction $transaction): self
    {
        if (!$this->transactions->contains($transaction)) {
            $this->transactions[] = $transaction;
            $transaction->setCustomer($this);
        }

        return $this;
    }

    public function removeTransaction(Transaction $transaction): self
    {
        if ($this->transactions->removeElement($transaction)) {
            // set the owning side to null (unless already changed)
            if ($transaction->getCustomer() === $this) {
                $transaction->setCustomer(null);
            }
        }

        return $this;
    }

    public function getTransactionsCount(): int
    {
          return $this->transactions->count();
    }

    public function getProfit(): float
    {
        $sum = 0;
        foreach($this->transactions as $transaction) {
            $sum += $transaction->getResult();
        }

        return $sum;
    }
}

src/Entity/Transaction.php
<?php

namespace App\Entity;

use App\Repository\TransactionRepository;
use DateTimeInterface;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use JetBrains\PhpStorm\Pure;

/**
 * @ORM\Entity(repositoryClass=TransactionRepository::class)
 */
class Transaction
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private ?int $id;

    /**
     * @ORM\Column(type="datetime")
     */
    private DateTimeInterface $date;

    /**
     * @ORM\Column(type="float")
     */
    private float $price = 0;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private float $tax = 0;

    /**
     * @ORM\Column(type="boolean")
     */
    private bool $isClosed = false;

    /**
     * @ORM\ManyToOne(targetEntity=Customer::class, inversedBy="transactions")
     */
    private ?Customer $customer;


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDate(): ?DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function getPrice(): float
    {
        return $this->price ?? 0;
    }

    public function setPrice(float $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getTax(): float
    {
        return $this->tax ?? 0;
    }

    public function setTax(?float $tax): self
    {
        $this->tax = $tax;

        return $this;
    }

    public function getIsClosed(): bool
    {
        return $this->isClosed;
    }

    public function setIsClosed(bool $isClosed): self
    {
        $this->isClosed = $isClosed ?? false;

        return $this;
    }

    public function getCustomer(): ?Customer
    {
        return $this->customer;
    }

    public function setCustomer(?Customer $customer): self
    {
        $this->customer = $customer;

        return $this;
    }

    public function getResult(): float
    {
        return $this->price - $this->tax;
    }
}

src/Form/CustomerType.php
<?php

namespace App\Form;

use App\Entity\Customer;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Validator\Constraints as Assert;


class CustomerType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('firstname')
            ->add('lastname')
            ->add('pseudo', TextType::class, [
                'constraints' => [
                    new Assert\NotBlank(),
                ],
            ])
            ->add('adress')
            ->add('postCode')
            ->add('city')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Customer::class,
        ]);
    }
}

src/Controller/CustomerController.php
<?php

namespace App\Controller;

use App\Entity\Customer;
use App\Form\CustomerType;
use App\Repository\CustomerRepository;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/customer')]
class CustomerController extends AbstractController
{
    #[Route('/{page<\d+>?1}', name: 'customer_index', methods: ['GET'])]
    public function index(
        Request $request,
        CustomerRepository $customerRepository,
        PaginatorInterface $paginator,
        int $page,
    ): Response
    {
        $filter = $request->get('search');

        $pagination = $paginator->paginate(
            $customerRepository->findPseudoSearch($filter),
            $page,
            10
        );

        $currentPageNumber = $pagination->getCurrentPageNumber();
        $numberOfPages = ceil($pagination->getTotalItemCount() / $pagination->getItemNumberPerPage());

        return $this->render('customer/index/main.html.twig', [
            'customers' => $pagination,
            'currentPageNumber' => $currentPageNumber,
            'numberOfPages' => $numberOfPages,
        ]);
    }

    #[Route('/new', name: 'customer_new', methods: ['GET', 'POST'])]
    public function new(Request $request): Response
    {
        $customer = new Customer();
        $form = $this->createForm(CustomerType::class, $customer);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($customer);
            $entityManager->flush();

            return $this->redirectToRoute('customer_index');
        }

        return $this->render('customer/new.html.twig', [
            'customer' => $customer,
            'form' => $form->createView(),
        ]);
    }

    #[Route('/history/{id}', name: 'customer_show', methods: ['GET'])]
    public function show(Customer $customer): Response
    {
        return $this->render('customer/show/main.html.twig', [
            'customer' => $customer,
        ]);
    }

    #[Route('/{id}/edit', name: 'customer_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Customer $customer): Response
    {
        $form = $this->createForm(CustomerType::class, $customer);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->addFlash('success', 'Successfully uploaded');
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('customer_index');
        }

        return $this->render('customer/edit.html.twig', [
            'customer' => $customer,
            'form' => $form->createView(),
        ]);
    }

    #[Route('/{id}', name: 'customer_delete', methods: ['DELETE'])]
    public function delete(Request $request, Customer $customer): Response
    {
        if ($this->isCsrfTokenValid('delete'.$customer->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($customer);
            $entityManager->flush();
        }

        return $this->redirectToRoute('customer_index');
    }
}

templates/customer/show/header.html.twig
<div class="lg:flex lg:items-center lg:justify-between py-6 px-8">
    <div class="flex-1 min-w-0">
        <h2 class="text-2xl font-bold leading-7 text-gray-900 sm:text-3xl sm:truncate">
            {{ customer.pseudo }}
        </h2>
        <div class="mt-1 flex flex-col sm:flex-row sm:flex-wrap sm:mt-0 sm:space-x-6">
            <div class="mt-2 flex items-center text-sm text-gray-500">
                <!-- Heroicon name: currency-dollar -->
                <svg class="flex-shrink-0 mr-1.5 h-5 w-5 text-gray-400" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                    <path d="M8.433 7.418c.155-.103.346-.196.567-.267v1.698a2.305 2.305 0 01-.567-.267C8.07 8.34 8 8.114 8 8c0-.114.07-.34.433-.582zM11 12.849v-1.698c.22.071.412.164.567.267.364.243.433.468.433.582 0 .114-.07.34-.433.582a2.305 2.305 0 01-.567.267z" />
                    <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm1-13a1 1 0 10-2 0v.092a4.535 4.535 0 00-1.676.662C6.602 6.234 6 7.009 6 8c0 .99.602 1.765 1.324 2.246.48.32 1.054.545 1.676.662v1.941c-.391-.127-.68-.317-.843-.504a1 1 0 10-1.51 1.31c.562.649 1.413 1.076 2.353 1.253V15a1 1 0 102 0v-.092a4.535 4.535 0 001.676-.662C13.398 13.766 14 12.991 14 12c0-.99-.602-1.765-1.324-2.246A4.535 4.535 0 0011 9.092V7.151c.391.127.68.317.843.504a1 1 0 101.511-1.31c-.563-.649-1.413-1.076-2.354-1.253V5z" clip-rule="evenodd" />
                </svg>
                {{ customer.profit }}€
            </div>
        </div>
    </div>
    <div class="mt-5 flex lg:mt-0 lg:ml-4">
        <span>
          <a href="{{ path('customer_edit', {'id': customer.id}) }}" class="btn-medium btn-gray">
            <!-- Heroicon name: pencil -->
            <svg class="-ml-1 mr-2 h-5 w-5 text-gray-500" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
              <path d="M13.586 3.586a2 2 0 112.828 2.828l-.793.793-2.828-2.828.793-.793zM11.379 5.793L3 14.172V17h2.828l8.38-8.379-2.83-2.828z" />
            </svg>
            Edit
          </a>
        </span>
    </div>
</div>

<!-- Customer information -->
{% if customer.firstname is not null or customer.lastname is not null or customer.adress is not null %}
    <div class="px-4 py-5 sm:px-8 sm:mb-8 mb-6">
        <dl class="grid grid-cols-1 gap-x-4 gap-y-8 sm:grid-cols-2">
            {% if customer.firstname is not null or customer.lastname is not null %}
                <div class="sm:col-span-1">
                    <dt class="text-sm font-medium text-gray-500">
                        Nom
                    </dt>
                    <dd class="mt-1 text-sm text-gray-900">
                        {{ customer.firstname }} {{ customer.lastname }}
                    </dd>
                </div>
            {% endif %}

            {% if customer.adress is not null or customer.postCode is not null or customer.city is not null%}
                <div class="sm:col-span-1">
                    <dt class="text-sm font-medium text-gray-500">
                        Adresse
                    </dt>
                    <dd class="mt-1 text-sm text-gray-900">
                        {{ customer.adress }} {{ customer.postCode }} {{ customer.city }}
                    </dd>
                </div>
            {% endif %}
        </dl>
    </div>
{% endif %}

templates/customer/show/main.html.twig
{% extends 'base.html.twig' %}

{% block title %}Customer{% endblock %}

{% block body %}
    <!-- Header -->
    {{ include('customer/show/header.html.twig', {'customer': customer}) }}

    <!-- Customer table (only on smallest breakpoint) -->
    {{ include('customer/show/smallest_breakpoint.html.twig', {'customer': customer}) }}

    <!-- Customer table (small breakpoint and up) -->
    {{ include('customer/show/small_breakpoint_and_up.html.twig', {'customer': customer}) }}

{% endblock %}

templates/customer/show/small_breakpoint_and_up.html.twig
<div class="hidden sm:block">
    <div class="align-middle inline-block min-w-full border-b border-gray-200">
        <table class="min-w-full">
            <thead>
            <tr class="border-t border-gray-200">
                <th>Date</th>
                <th>Prix Vente</th>
                <th>Commission</th>
                <th>Profit</th>
            </tr>
            </thead>
            <tbody class="bg-white divide-y divide-gray-100">
            {% for transaction in customer.transactions %}
                <tr>
                    <td class="md:table-cell px-6 py-3 whitespace-nowrap text-sm text-gray-500 text-left">
                        {{ transaction.date|date("d/m/Y") }}
                    </td>
                    <td class="md:table-cell px-6 py-3 whitespace-nowrap text-sm text-gray-500 text-left">
                        {{ transaction.price }}€
                    </td>
                    <td class="md:table-cell px-6 py-3 whitespace-nowrap text-sm text-gray-500 text-left">
                        {{ transaction.tax }}€
                    </td>
                    <td class="md:table-cell px-6 py-3 whitespace-nowrap text-sm text-gray-500 text-left">
                        {{ transaction.result }}€
                    </td>
                </tr>
            {% else %}
                <tr>
                    <td colspan="3" class="py-4 px-4 text-sm text-gray-500">no records found</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
</div>

templates/customer/show/smallest_breakpoint.html.twig
<div class="sm:hidden">
    <div class="px-4 sm:px-6">
        <h2 class="text-gray-500 text-xs font-medium uppercase tracking-wide">
            Ventes
        </h2>
    </div>
    <ul class="mt-3 border-t border-gray-200 divide-y divide-gray-100">
        {% for transaction in customer.transactions %}
            <li>
                <a href="#" class="group flex items-center justify-between px-4 py-4 hover:bg-gray-50 sm:px-6">
                    <span class="flex items-center truncate space-x-3">
                        <span class="font-medium truncate text-sm leading-6 text-gray-600">
                            {{ transaction.date|date("d/m/Y") }}
                        </span>
                        <span class="font-medium truncate text-sm text-gray-600">
                            {{ transaction.result }}€
                        </span>
                    </span>
                    <!-- Heroicon name: chevron-right -->
                    <svg class="ml-4 h-5 w-5 text-gray-400 group-hover:text-gray-500" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                        <path fill-rule="evenodd" d="M7.293 14.707a1 1 0 010-1.414L10.586 10 7.293 6.707a1 1 0 011.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0z" clip-rule="evenodd" />
                    </svg>
                </a>
            </li>
        {% else %}
            <tr>
                <td colspan="3" class="py-4 px-4 text-sm text-gray-500">no records found</td>
            </tr>
        {% endfor %}
    </ul>
</div>